#!/bin/bash
config_path="/opt/lich/config.json"

addgroup --system torrent-files
adduser --system --no-create-home --ingroup torrent-files lich
if id plex >/dev/null 2>&1; then
  echo "Found plex user. Adding it to torrent-files group."
  usermod -aG torrent-files plex
fi

mkdir -p /media/lich/{movies,series,unsorted,inprogress}
chgrp -R torrent-files /media/lich
find /media/lich -type d -exec chmod 2775 {} \;
find /media/lich -type f -exec chmod 664 {} \;

mkdir -p /opt/lich/db
chmod 700 /opt/lich/db
chown lich:torrent-files /opt/lich

echo "Lich server has been successfully installed."
echo "The default media directories are located at /media/lich."

if [[ -e /opt/lich/config.json ]]; then
  echo "Existing config is found at $config_path. Enabling and starting the service."
  systemctl enable lich
  systemctl start lich
else
  cp /opt/lich/config_example.json /opt/lich/config.json
  echo "Example config file is created at $config_path."
  echo "Please edit the config file and enable the service by running 'systemctl enable lich'."
fi
