name: Release packages

permissions:
  contents: write

on:
  push:
    tags:
    - 'v*'


jobs:
  build_packages:
    name: Build binaries and packages
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y build-essential
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - name: Override version
      run: echo "${GITHUB_REF_NAME}" | sed -e 's/^v//' > VERSION
    - name: Build
      run: make all
    - name: Rename the package
      run: mv bin/lich.deb bin/lich_amd64.deb
    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/lich_amd64.deb
          config/config_example.json
          bin/lich_linux_amd64
          bin/lich_linux_arm64
          bin/lich_darwin_amd64
          bin/lich_darwin_arm64
